### PR TITLE
[CI] +ubuntu22 -ubuntu18

### PR DESCRIPTION
**Pull request by ppenzin**
Drop Ubuntu 18.04 from Azure testing, as it is getting deprecation warnings now (also Canonical stops maintaining software packages after four years, I believe). Add Ubuntu 22.04.

### CODE REVIEW

**Comment by ppenzin** [comment]
I've built and ran Chakra on Ubuntu 22, though not in the configurations that failed. Investigating.

_Update:_ I can't repro those yet. Have an idea for what might be causing the `-Werror` issue, but not for the other one. Will re-run.

**Comment by ppenzin** [comment]
Now we have the same error in both jobs - it fails to regen bytecode and I'm not yet sure why.

_Update:_ Hm, I thought I habitually ran on Ubuntu 22.04, but it turns out it was 20.04, currently upgrading.

_Update 2:_ Change above fixes the compilation error. I can reproduce bytecode regeneration error, it is a crash. I am going to try to recompile affected files with "passing" flags, if I can isolate them.

**Comment by rhuanjl** [comment]
This is very strange, is ch crashing completely when regenerating the bytecode?

**Comment by ppenzin** [comment]
> This is very strange, is ch crashing completely when regenerating the bytecode?

Yes. I am trying to narrow that down, there might be something that upsets clang somehow.

**Comment by ppenzin** [comment]
As a fun experiment maybe we should build with ToT clang periodically to watch out for errors like this.

**Comment by rhuanjl** [comment]
> > This is very strange, is ch crashing completely when regenerating the bytecode?
> 
> Yes. I am trying to narrow that down, there might be something that upsets clang somehow.

Cross posting from issue #6847 I think this is because the meaning of `auto` in some contexts has been changed by an update to C++ - from what I read this was seen as fixing an ambiguity of meaning and hence is applied retroactively whatever standards level you select.

I think we need to reduce/remove the use of `auto` in the `ImmutableList` header to fix this.

**Comment by rhuanjl** [comment]
Closing as superseded

**Pull request closed without merging**
