### PR TITLE
Attempt fix and enable for Ubuntu 22

### PR DESCRIPTION
**Pull request by rhuanjl**
Change from #6932 + enable CI for Ubuntu 22

### CODE REVIEW

**Comment by ppenzin** [comment]
I've played around with this, not sure if there is just one place where the alignment is needed, but hopefully we can figure this out.

**Comment by ShortDevelopment** [comment]
https://github.com/chakra-core/ChakraCore/issues/6847#issuecomment-2060084507

**Comment by ppenzin** [comment]
@rhuanjl I've added @ShortDevelopment's fix to the PR, but since it is your branch, feel free to remove/rework/change in anyway you want.

**Review by ppenzin — APPROVED** [review]

**Comment by ppenzin** [comment]
And I had to remove that fix, the issue is that MSVC doesn't like noinline attribute, so it has to be an ifdef or something like that - we can revisit. The code would work on Ubuntu and not necessary on Windows.

**Comment by ppenzin** [comment]
I've updated the workaround to hopefully work on MSVC, trying it out in #6977, though not sure it is the optimal solution in the long run.

**Comment by rhuanjl** [comment]
Planning to merge #6932 then we can follow up with a working version of this.

**Pull request closed without merging**
