### PR TITLE
Add debug type for Module Namespace

### PR DESCRIPTION
**Pull request by BickfordA**
I have been setting up the debugger from https://github.com/Microsoft/ChakraCore-Debugger and was having trouble debugging modules, as the debugger would crash when reading the type attibute (as it didn't have one).  Seems like that case never got added here.

### CODE REVIEW

**Comment by rhuanjl** [comment]
Thanks for the contribution @BickfordA please could you:

1. Sign our contribution agreement by adding your name and github userID to this file:
https://github.com/chakra-core/ChakraCore/blob/master/ContributionAgreement.md

2. Update the copyright at the top of the file you've changed to:
```
//-------------------------------------------------------------------------------------------------------
// Copyright (C) Microsoft. All rights reserved.
// Copyright (c) 2021 ChakraCore Project Contributors. All rights reserved.
// Licensed under the MIT license. See LICENSE.txt file in the project root for full license information.
//-------------------------------------------------------------------------------------------------------
```

**Comment by BickfordA** [comment]
Alright, I think those two issues should be squared away.

**Comment by rhuanjl** [comment]
Looks good to merge except for the merge conflict (someone else signed the contribution agreement) - please could you update to latest master to fix?

**Review by rhuanjl — APPROVED** [review]

**Comment by rhuanjl** [comment]
Thanks for the contribution.

**Pull request merged**
