### PR TITLE
Skip Array push fast path if prototype unsafe 

### LINKED ISSUE #6582: A question about Array.prototype.push
###### Version

chakra-1.11.24

###### Test case

```js
var arr = [];

Object.defineProperty(Array.prototype, '0', {
    get: function() {
        print('get');
        return 30;
    },
    set: function() {
        print('set');
        return 60;
    }
});

arr.push(1);
print('arr:', arr);
print('arr:', arr[0]);
```

###### Execution steps

    ./ChakraCore/out/Release/ch testcase.js

###### Output

```
arr: 1
arr: 1
```

###### Expected behavior

```
set
arr: get
30
get
arr: 30
```

###### Description

When executing the above test case, when executing `arr.push` in line 14, other engines (such as v8, SpiderMonkey, JavascriptCore, etc.) all call the `set` method defined in line 8, and then execute the `get` method defined in line 4. However, chakra does not seem to do this. Is this a bug in chakra implementation?

### PR DESCRIPTION
**Pull request by rhuanjl**
1. The Array.prototype.push fast path does not walk the prototype chain - great for speed but a problem if there's a getter/setter on it - skip the fast path if the prototype has anything "unusual" on it so that getters/setters will be called. Add a test case for this based on issue #6582 NOTE: there are 4 variants of "the fastpath" depending where Push is called from - 1 is from EntryPush (the default) the other 3 JavascriptArray::Push, JavascriptNativeIntArray::Push and JavascriptNativeFloatArray::Push are fallbacks from the JIT when it has inlined `push` but determined the inlined method is invalid. I've updated all 4 of these.

2. Fix two existing test cases that were relying on this incorrect behaviour
3. Remove the internal use of Array.prototype.push within Intl.js - now it follows the spec editing the Array prototype could have introduced undefined behaviour into Intl.js
4. Regen the Bytecode for the changes to Intl (also correct a small mistake in the bytecode Regen script - I'd indented the string used for the ByteCodeCacheReleaseFileVersion.h file without realising that it would be indented in the output file.

More detailed comments in commit messages.

@ppenzin @Fly-Style please could one of you take a look - this is fairly simple.

Fix #6582

### CODE REVIEW

**Comment by rhuanjl** [comment]
And a little ugh... CI failures are because Azure Pipelines Ubuntu-latest has ticked over to Ubuntu 20 and CC fails to build on it.

At a glance looks like some deprecated C++ features we're using - CC has a C++11 codebase which is a somewhat out of date standard to be on - perhaps we should look at cleaning up/removing deprecated features.

**Comment by rhuanjl** [comment]
EDIT: OUTDATED

Fix isn't sufficient - I've fixed the interpreter fast path but the JIT fast path is still broken - not sure why I missed that testing offline orriginaly can repro it now though - DO NOT MERGE (converted to draft)

**Comment by pleath** [comment]
Theoretically, the easiest way to fix this is to implement Array.prototype.push in JavaScript. Assuming the call gets inlined at hot call sites, we'd get the benefit of fast prototype-chain checking for setters and non-writable properties that we already get for "normal" property-adds.

**Comment by ppenzin** [comment]
> And a little ugh... CI failures are because Azure Pipelines Ubuntu-latest has ticked over to Ubuntu 20 and CC fails to build on it.
> 
> At a glance looks like some deprecated C++ features we're using - CC has a C++11 codebase which is a somewhat out of date standard to be on - perhaps we should look at cleaning up/removing deprecated features.

I don't know if adding flags controlling standard compliance would help. We can also explicitly pick Ubuntu 18 as a workaround while we figure out a permanent fix.

**Comment by ppenzin** [comment]
After taking a closer look at the failures, they seem to be coming from math function declarations in PAL, maybe we can use this as an opportunity to get rid of them; though as with all things PAL-related it can spin out of control.

**Comment by rhuanjl** [comment]
> Theoretically, the easiest way to fix this is to implement Array.prototype.push in JavaScript. Assuming the call gets inlined at hot call sites, we'd get the benefit of fast prototype-chain checking for setters and non-writable properties that we already get for "normal" property-adds.

I tried this but the performance with some of the benchmarks was dismal - I may go back to that approach but want to find a way to make it more performant than my first try at that.

**Comment by pleath** [comment]
Hm. Was the push call getting inlined in the regressed benchmarks? If not, that's probably the cause. If it is, it would be interesting to look at the jitted code for the inlined JavaScript versus the generated fast path.

**Comment by rhuanjl** [comment]
I've experimented a bit - the regression comes from something the fast path omits.

Per spec at the end of a push the array length should be set to its expected new value - in the case of a "normal" array this is not observable; but in the case of a pseudo-array of some kind OR an array with a setter on the prototype it can be.

So my JS implementation included `this.length = newLen;` and even though this is not changing the value in these cases it appears to result in lots of `BailOutFailedEquivalentTypeCheck` bailouts at run time.

**Comment by pleath** [comment]
I see. The bailouts kind of suggest that some important calls to push are not getting inlined. Is that the case? If they were inlined, I would expect us not to see so much polymorphism.

**Comment by rhuanjl** [comment]
**UPDATE: the rest of this comment is about abandoned alternative approaches and not what is actually in this PR (see next comment)**

It certainly inlines it in some places - I think part of the problem is the amount of indirection.

There are several heavily regressed benchmarks, the most extreme one is this one:
https://github.com/chakra-core/ChakraCore/blob/master/test/benchmarks/Octane/deltablue.js

With my original JS implementation that regressed by 45%.

Using a __chakralibrary native function to update the length instead of setting it directly it changed the regression to only 25% - still fairly significant though.

Alternatively sticking to the C++ implementation AND disabling the fast path the regression is ~30%. None of these options seem good.

**Comment by rhuanjl** [comment]
In light of the poor performance and inlining trying to do this with self-hosted JS I've stuck with native and fixed the fast path. 

The issue with the JIT fast path was not actually in the JIT but the helpers it fell back to when fast path was invalid didn't check for edited prototype. Original comment above updated with detail of actual fix.

@ppenzin @Fly-Style this is ready for review

**Comment by pleath** [comment]
Is the check for ES5 array good enough? How about if there is a non-array object in the prototype chain?

**Comment by rhuanjl** [comment]
> Is the check for ES5 array good enough? How about if there is a non-array object in the prototype chain?

The `HasAnyES5ArrayInPrototypeChain` includes looking for Proxies and objects with arrays - happy to add some extra test cases if there's anything else you think I should be sure it's checking for.

**Comment by pleath** [comment]
I guess the meaning of the method has drifted a little from its name... The change looks good to me, then. Thanks.

**Comment by rhuanjl** [comment]
@ppenzin nothing specific depending on it but please could you review this when you have time?

**Comment by ppenzin** [comment]
@pleath I don't know why you were dropped as a member of the repo, but I am trying to add you back so that we can request you on code reviews sometimes ;)

**Review by ppenzin — APPROVED** [review]

**Pull request merged**
