### PR TITLE
Introduce MSVC CI

### PR DESCRIPTION
**Pull request by ppenzin**
Add MSVC CI jobs, testing on latest Windows VM image using provided build and test wrappers.

For #6547

### CODE REVIEW

**Comment by rhuanjl** [comment]
Hmm any obvious reason why the CI hasn't triggered here?

**Comment by ppenzin** [comment]
It failed parsing YAML. I got a little ahead of myself on the syntax after finding an example online :)

**Comment by ppenzin** [comment]
Finally. All follow up commits are just fixing mistakes in the initial one, we don't need to preserve their messages if testing succeeds.

I am assigning 5 parallel tasks to the CMake job and 5 to MSVC. We can try to combine them into one big job, it should yield faster builds, but at expense of readability.

**Comment by ppenzin** [comment]
For now, I am going to give 6 jobs to CMake (covering all needed) and the remaining 4 to Visual Studio, this should work as VS builds are much faster. I am also going to rebase all changes together.

**Comment by rhuanjl** [comment]
Looking at the speed comparisons - those windows builds are crazy fast.

**Stand out differences:**
1. the runtests.py testrunner prints a result for every test, the windows testrunner rl.exe only prints a summary and any failures
2. runtests.py seems to be running all tests 3 times with 3 different sets of flags, rl.exe appears to only do all the tests twice with 2 sets of flags

**Comment by ppenzin** [comment]
Maybe we should start with hiding the output - it produces enormous amount of text. If rl.exe cap number of concurrent tests it might also be the reason why it is faster.

**Comment by rhuanjl** [comment]
> Maybe we should start with hiding the output - it produces enormous amount of text. If rl.exe cap number of concurrent tests it might also be the reason why it is faster.

Testing offline the excess output vanishes if runtests.py is called without a --logfile parameter - I don't want to open a PR because I'll delay your updates but two changes to try updating test/CMakeLists.txt with:
1. Remove `--logfile ${CMAKE_BINARY_DIR}/check.log` from the command? (This should drastically reduce the logging)
3. Add `-j=4` to it to make it use 4 threads which is what the windows test runner does?

Edit: tried this and it didn't work. BUT a slight tweak to runtests.py did do it - see #6559

**Review by rhuanjl — APPROVED** [review]

**Comment by ppenzin** [comment]
@Fly-Style I am going to merge, but will definitely address any feedback in a follow-up PR.

**Pull request merged**
