### PR TITLE
Sign Contribution Agreement

### PR DESCRIPTION
**Pull request by ppenzin**

### CODE REVIEW

**Comment by ppenzin** [comment]
There are some weird failures, and it looks like this started after CLA check got added. If we are going to run the CLA check this way we might have to delay the CI until the CLA is signed. If we are going to check the file in the root directory, this should not be the issue.

CC @rhuanjl @Fly-Style

**Comment by ppenzin** [comment]
Let's do a clopenning to see if OSX Release With Debug job is going to succeed after I've signed the CLA.

**Comment by ppenzin** [comment]
This confirms my suspicion that CLA assistant is introducing some interference with Azure CI - we need to either have Azure CI run only if CLA check succeeds (which is what the old CI did, by the way), or roll the check into CI.

**Comment by rhuanjl** [comment]
Figured we may as well merge this

**Pull request merged**
