### PR TITLE
[don't merge] Continuous Integration: introduce a failing test

### PR DESCRIPTION
**Pull request by ppenzin**
Introduce a failing test (for a bug which is still open) to see if CI is going to catch it.

### CODE REVIEW

**Comment by rhuanjl** [comment]
I noticed this yesterday - there is something wrong with the names of the test variants at least on macOS and Linux.

The "Interpreted" variant isn't purely interpreted it can trigger the JIT - this test case hits an assertion in the JIT and error'd on the "Interpreted" variant. Conversely the "Dynopogo" variant that is meant to thoroughly test the JIT doesn't always - in this case it did not trigger the assertion.

**Comment by ppenzin** [comment]
Yeah, this is odd, maybe that is why there were so many variants in the old CI. I definitely did not expect release+debug to pass, need to look deeper into this.

**Comment by rhuanjl** [comment]
> Yeah, this is odd, maybe that is why there were so many variants in the old CI. I definitely did not expect release+debug to pass, need to look deeper into this.

The Release with Debug info build doesn't have assertions in it.

The reason to test it as well as Debug is that it should largely behave the way a Release build does BUT it has the necessary hooks for the test suite which the release build does not have.

**Comment by ppenzin** [comment]
Going to close and reopen to see what Windows CI would think about this.

**Comment by rhuanjl** [comment]
Hits the same assertion in all the debug builds. But runs to completion in the test builds - curious I'm surprised it doesn't segfault.

**Comment by ppenzin** [comment]
I don't think it is a truly 'fatal' error - just one of the passes leaves some registers behind.

**Comment by rhuanjl** [comment]
Tested offline - the originally test case from the issue segfaults. Whereas your simplified one hits the same assertion BUT doesn't seg.

**Comment by ppenzin** [comment]
This confirms that CI is catching what we are expecting it to catch, should probably close this PR.

**Pull request closed without merging**
