### PR TITLE
Fix issue#6982 -- PM128A should be a pointer to 16-byte aligned M128U, not a 16-byte aligned pointer.

### PR DESCRIPTION
**Pull request by EmployedRussian**

### CODE REVIEW

**Review by ppenzin — COMMENTED** [review]
After thinking for a bit I think you are right, declspec_align applies to the pointer when it should not.

**Comment by ppenzin** [comment]
#6982  (for convenience)

**Review by ppenzin — APPROVED** [review]
Looks good to me. Upstream (dotnet) PAL [got rid of the extra layer of pointers](https://github.com/dotnet/runtime/commit/11be31e7a886a434fbd15bda1a0c5c84b4fd5051) by moving alignment to struct declaration above the line, though that requires some extra changes in other places.

@rhuanjl what do you think?

**Comment by rhuanjl** [comment]
> Looks good to me. Upstream (dotnet) PAL [got rid of the extra layer of pointers](https://github.com/dotnet/runtime/commit/11be31e7a886a434fbd15bda1a0c5c84b4fd5051) by moving alignment to struct declaration above the line, though that requires some extra changes in other places.
> 
> 
> 
> @rhuanjl what do you think?

Long term I'd like to get rid of more PAL if we can but this seems fine to me for now; I went ahead and merged it - can always revisit if we see further problems.

**Pull request merged**
