### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by abatishchev**
Fixed casing for some names and terms

### CODE REVIEW

**Comment by rhuanjl** [comment]
Thanks for the PR @abatishchev 

Please could you also sign our contribution agreement? I know this is just a simple change but we ask for it for anything:
Add a commit that puts your name and github username at the bottom of this file in the same format as the ones already there: https://github.com/chakra-core/ChakraCore/blob/master/ContributionAgreement.md

**Comment by abatishchev** [comment]
Hi @rhuanjl, do I need to sign it if I contribute as a Microsoft employee? I'm, my internal alias is alexbat.

**Comment by rhuanjl** [comment]
Ideally yes - Microsoft are no longer maintaining CC - as it's been discontinued as a product see #6384 for more info if interested.

The piece about exceptions for contributions on behalf of Microsoft was to cover any final contributions Microsoft made before ending support.

**Comment by abatishchev** [comment]
Not a lawyer, but the first paragraph says I don't need to sign.
And to sign, I need to involve lawyers. As an employee, can't just sign. Last time it took a month to get approved (

**Comment by rhuanjl** [comment]
You don't have to sign if you're contributing on behalf of microsoft and the work is covered by the existing license in License.txt.

(I didn't expect that as - MS said they were ending all support/work on CC)

That paragraph covers the situation if your contribution is part of your job for MS but not if you happen to be an MS employee but this is something you've done on your own time.

**Comment by abatishchev** [comment]
hi @rhuanjl,
Let me reiterate my point:

I'm contributing this one minor change on behalf of Microsoft and under the existing MIT license but that Microsoft is indeed no longer supporting the project.

I hope it'll be ok to check it in. Otherwise please close the PR.

**Comment by abatishchev** [comment]
Please either accept the PR or close it.

**Comment by ppenzin** [comment]
I feel like since the change is really minor and you are contributing on behalf of Microsoft (even if it does not officially provide support) it is OK to merge this in.

**Pull request merged**
