### PR TITLE
Allow `undefined` in `TypedArray.prototype.sort(comparefn)`

### LINKED ISSUE #6503: An issue about the TypedArray.prototype.sort().
A typeerror occurred in ChakraCore when I passed an undefined parameter in TypedArray.prototype.sort(), but other engines, such as V8 and quickjs, did not throw an error. Therefore, I think there may be a problem here.

**version**

1.11.19

**command**

```javascript
ChakraCore/out/Debug/ch testcase.js
```

**testcase**

```javascript
var NISLFuzzingFunc = function(){
    var a = new Uint32Array(1);
    var b = a.sort(undefined);
}
NISLFuzzingFunc();
```

**output**

```javascript
TypeError:[TypedArray].prototype.sort: argument is not a Function object.
```

**expected behavior**

```javascript
No error occurred.
``` 
Contributor : @Haobin-Lee

### PR DESCRIPTION
**Pull request by ShortDevelopment**
According to the spec, `TypedArray.prototype.sort(comparefn)` should allow `comparefn` to be `undefined`.

In this case `.sort(undefined)` should be equivalent to `.sort()`.
See https://tc39.es/ecma262/#sec-%typedarray%.prototype.sort

Before it threw a `TypeError`.

@rhuanjl 

Fix #6503

### CODE REVIEW

**Comment by rhuanjl** [comment]
This looks good (though waiting on tests passing).

At a quick look I'm struggling to see many tests for typed array sort - I wonder if this bug was not caught earlier because of generally poor test coverage around this area.

**Comment by ShortDevelopment** [comment]
May be...
There does not seem to be any test that is specific to `sort`.
https://cs.github.com/chakra-core/ChakraCore?q=path%3A%2Ftest%2Ftypedarray%2F*+sort

**Comment by rhuanjl** [comment]
More typedarray sort tests would be nice to have but not necessary to merge this, hence merged.

Thank you for the contribution.

**Review by rhuanjl — APPROVED** [review]

**Comment by ShortDevelopment** [comment]
> More typedarray sort tests would be nice to have but not necessary to merge this, hence merged.

Sorry, I didn’t get that 🙈.
I’ll try to come up with some good testcases…

**Comment by rhuanjl** [comment]
I wasn't necessarily saying you should add more tests just that we should have them.

**Comment by ShortDevelopment** [comment]
No problem, I have time

**Pull request merged**
