### PR TITLE
Fixed issue when syntax error is not thrown when an expression within if is comma-terminated

### PR DESCRIPTION
**Pull request by ylukomskyi**
## Link to the issue
https://github.com/chakra-core/ChakraCore/issues/6377

## Details
The part of the parser that processes if statements has been extended with the additional check of `m_deferCommaError`. When it is `true` then a syntax error is thrown.

The sample of the code that was considered correct before should throw now
```
var func = function() {
    var f = 0;
    if (f === 0,) {
        print("run_here");
    }
}
func();
```

### CODE REVIEW

**Review by rhuanjl — APPROVED** [review]
Thanks for the contribution @ylukomskyi  this Looks Good To Me.

Unfortunately merging is blocked until our new CI is setup - which will likely be a few days. I'll plan to merge this as soon as the CI is sorted.

**Review by ppenzin — APPROVED** [review]

**Comment by rhuanjl** [comment]
@ylukomskyi please could you add a second commit that signs our new contributor agreement
(adding your name and github username to here under mine in the same format): https://github.com/chakra-core/ChakraCore/blob/master/Contribution%20Agreement.md

Then I will take this in.

**Comment by ylukomskyi** [comment]
@rhuanjl added a new commit, thanks

**Comment by rhuanjl** [comment]
Adopted as #6580 to rebase and merge

**Comment by rhuanjl** [comment]
Thanks for the contribution @ylukomskyi sorry for the delay in merging it

**Pull request closed without merging**
