### PR TITLE
Try this==null fix

### PR DESCRIPTION
**Pull request by ppenzin**
Adding contents of #6975 as well as it sets up the pipeline that would expose the miscompilation issue.

### CODE REVIEW

**Comment by ppenzin** [comment]
This is just supplemental to #6975

**Comment by rhuanjl** [comment]
I think we should give @EmployedRussian a chance to have his version of the first bug merged before we merge our adopted versions - but.... So good to have finally got to the bottom of the Ubuntu 22 issues. Thank you for the time you've put into this.

**Comment by rhuanjl** [comment]
Do you want to replace my 3 old commits above with the below 2 and then merge this so we have Ubuntu 22 working for now, or would you rather we do a better fix straight off?

https://github.com/chakra-core/ChakraCore/commit/4bae197849d8f597c3781ffec25d18aaf931ef29
and
https://github.com/chakra-core/ChakraCore/commit/61c011a568d1659cae158ed4ab57a7f4a67ce0a7

**Comment by ppenzin** [comment]
I think we should unblock Ubuntu 22, though I will probably try to refactor the code.

**Review by rhuanjl — APPROVED** [review]
Seems good to me for now; I'll open a PR with the CI once this and your other PR are merged.

**Pull request merged**
