### PR TITLE
Create automated CLA checking

### PR DESCRIPTION
**Pull request by Fly-Style**
This PR introduces automated CLA checking using  [CLA Assistant](https://cla-assistant.io/) service.
I create CLA there, and connect newly-created agreement to CC's repository. 
I used this service on my previous projects and it worked fine 2 years ago. I'll gonna check it now.

### CODE REVIEW

**Comment by Fly-Style** [comment]
As you can see, it works fine.
I can launch a refresh process for all PR's to check signed CLA.

**Comment by rhuanjl** [comment]
Couple of questions:
1. How does this work - is it checking against the agreement we have in the repository to see who has signed it or is it linking to a copy somewhere else?
2. How/where can we review the setup for this - this PR just adds a badge to the readme right?

Other thoughts:
1. Before we merge I'd like to see what it says to a PR from someone who hasn't signed
2. I'm 50/50 if we should re-launch it on old PRs, anything submitted before the migration to our control in December was submitted under the Microsoft CLA and can be considered copyright microsoft and already appropriately licensed - we only need this for stuff submitted after the migration (i.e. future PRs + #6551 and #6571  )

**Comment by Fly-Style** [comment]
> 1. How does this work - is it checking against the agreement we have in the repository to see who has signed it or is it linking to a copy somewhere else?

Yes, it is not agreement that we have in repository : unfortunately, it works only with gist. 
This service copies CLA text from [there](https://gist.github.com/Fly-Style/0e98d48fac1c120fa019b59691e3d5d2) and wraps by CLA management system.

> 2. How/where can we review the setup for this - this PR just adds a badge to the readme right?

Yes, if someone want to sign it without creating a PR.
All work was done in a background on https://cla-assistant.io .

**Comment by ppenzin** [comment]
The list is in the app?

Having status of CLA signing not depend on the state of the repo has its benefits - that means that PR would not have to be rebased when the author signs the agreement.

**Comment by Fly-Style** [comment]
@rhuanjl @ppenzin  any thoughts?

**Comment by rhuanjl** [comment]
@Fly-Style we've been comparing with an alternative - see #6578

**Comment by rhuanjl** [comment]
Superseded by #6578

**Pull request closed without merging**
