### PR TITLE
To fix issue #6984, #include <stdarg.h>

### PR DESCRIPTION
**Pull request by EmployedRussian**
The file uses va_arg etc, so it should #include <stdarg.h>

For #6984

### CODE REVIEW

**Review by ppenzin — APPROVED** [review]
@EmployedRussian, sorry, added a "for" line to OP, that way Github would understand this is related.

The build "breakage" in CI is a check for the new copyright notice - we started doing that after we took over maintenance from Microsoft. The new notice is 

```
// ChakraCore/Pal
// Contains portions (c) copyright Microsoft, portions copyright (c) the .NET Foundation and Contributors
// and edits (c) copyright the ChakraCore Contributors.
// See THIRD-PARTY-NOTICES.txt in the project root for .NET Foundation license
// Licensed under the MIT license. See LICENSE.txt file in the project root for full license information.
```

It should replace these two lines:

```
// Copyright (c) Microsoft. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.
```

**Comment by rhuanjl** [comment]
> @EmployedRussian, sorry, added a "for" line to OP, that way Github would understand this is related.
> 
> The build "breakage" in CI is a check for the new copyright notice - we started doing that after we took over maintenance from Microsoft. The new notice is
> 
> ```
> // ChakraCore/Pal
> // Contains portions (c) copyright Microsoft, portions copyright (c) the .NET Foundation and Contributors
> // and edits (c) copyright the ChakraCore Contributors.
> // See THIRD-PARTY-NOTICES.txt in the project root for .NET Foundation license
> // Licensed under the MIT license. See LICENSE.txt file in the project root for full license information.
> ```
> 
> It should replace these two lines:
> 
> ```
> // Copyright (c) Microsoft. All rights reserved.
> // Licensed under the MIT license. See LICENSE file in the project root for full license information.
> ```

I can't remember if it was a conscious decision to only update copyright headers on files we've changed or if it was just the pattern we've slipped into - I wonder if we should run a script to update all copyright headers so this stops being a regular issue... If yes perhaps we could ignore the test failure and force merge this then I'll follow up with a generated PR to fix all the remaining copyright headers.

**Comment by ppenzin** [comment]
I can fix that with a bit of write permissions magic! :wink:

**Comment by ppenzin** [comment]
I added the correct license, but the tool didn't like it anyway. I think I will merge and open a PR to fix that

**Comment by ppenzin** [comment]
I was adding a line at the beginning only containing `//`, that is why the tool was not picking it up.

**Comment by rhuanjl** [comment]
Thanks for fixing this @EmployedRussian

**Pull request merged**
